# This workflow is to create a release PR for a specified version.
# It can be trigger manually with the version as an input.
# Once the PR is merged into main branch the release.yml workflow
# will start the release process.
name: 'Release PR'

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Enter version (Eg: 1.3.0)'
                required: true

permissions: {}
jobs:
    release-please:
        permissions:
            contents: write # to create release commit (google-github-actions/release-please-action)
            pull-requests: write # to create release PR (google-github-actions/release-please-action)

        runs-on: ubuntu-latest
        steps:
            - name: Display Release version
              run: echo "Creating release PR for ${{ github.event.inputs.version }}"

            - name: Create Release PR
              uses: google-github-actions/release-please-action@v3
              id: release
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  release-type: node
                  package-name: nepali-datetime
                  release-as: '${{ github.event.inputs.version }}'
                  pull-request-title-pattern: 'chore: release v${version}'
                  pull-request-header: 'Release PR for v${{ github.event.inputs.version }}'
                  changelog-types: >
                      [
                        {"type":"fix","section":"Bug Fixes"},
                        {"type":"feat","section":"Features"}
                      ]
